[build]
  functions="functions"

[[redirects]]
  from = "/api/*"
  to = "https://api.freecodecamplisbon.org/.netlify/functions/:splat"
  status = 200
  force = true

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"